services:
  iotproject.blazordashboard:
    image: ${DOCKER_REGISTRY-}iotprojectblazordashboard
    build:
      context: .
      dockerfile: IotProject.BlazorDashboard/Dockerfile
    ports:
        - 8080:8080
        - 8081:8010
